services:
  notes-mysql:
    image: mysql:9.2.0
    container_name: notes-mysql
    env_file:
      - kustomize/base/secrets/mysql.env
    ports:
      - 3309:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - notes

  notes-rustfs:
    image: rustfs/rustfs:latest
    container_name: notes-rustfs
    env_file: kustomize/base/secrets/rustfs.env
    volumes:
      - rustfs_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - notes

  notes-backend:
    image: ghcr.io/alexanderboldt/notes-backend:5.3.0
    container_name: notes-backend
    ports:
      - 4000:4000
    env_file:
      - kustomize/base/secrets/mysql.env
      - kustomize/base/secrets/notes.env
    depends_on:
      - notes-mysql
      - notes-rustfs
    networks:
      - notes

volumes:
  mysql_data:
  rustfs_data:

networks:
  notes:
    name: notes
