apiVersion: v1
kind: Service
metadata:
  name: notes-frontend
spec:
  type: NodePort
  selector:
    app: notes-frontend
  ports:
    - port: 80 # internal cluster port
      targetPort: 80
      nodePort: 30100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-frontend
spec:
  selector:
    matchLabels:
      app: notes-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: notes-frontend
    spec:
      containers:
        - name: notes-frontend
          image: ghcr.io/alexanderboldt/notes-frontend-kubernetes:0.4.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
