apiVersion: v1
kind: Service
metadata:
  name: notes-mysql
spec:
  selector:
    app: notes-mysql
  ports:
    - port: 3306 # internal cluster port
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: notes-mysql
spec:
  selector:
    matchLabels:
      app: notes-mysql
  serviceName: notes-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: notes-mysql
    spec:
      containers:
        - name: notes-mysql
          image: mysql:9.2.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: notes-mysql-secret
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: notes-mysql-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: notes-mysql-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
