namespace: notes

resources:
  - namespace.yml
  - mysql/statefulset.yml
  - rustfs/statefulset.yml
  - notes/deployment-backend.yml
  - notes/deployment-frontend.yml

secretGenerator:
  - name: notes-mysql-secret
    envs:
      - secrets/mysql.env
  - name: notes-rustfs-secret
    envs:
      - secrets/rustfs.env
  - name: notes-backend-secret
    envs:
      - secrets/notes.env
